# Generated by Django 2.0.7 on 2018-07-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMergeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MergeOID', models.CharField(max_length=5)),
                ('CliOIDs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CliOID', models.CharField(max_length=5)),
                ('Side', models.CharField(max_length=10)),
                ('Symbol', models.CharField(max_length=10)),
                ('Qty', models.CharField(max_length=100)),
                ('Dest', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
                ('Tif', models.CharField(max_length=10)),
                ('Otyp', models.CharField(max_length=10)),
                ('FixTags', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NewStreetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLiOID', models.CharField(max_length=5)),
                ('StrOID', models.CharField(max_length=5)),
                ('Side', models.CharField(max_length=10)),
                ('Symbol', models.CharField(max_length=10)),
                ('Qty', models.CharField(max_length=100)),
                ('Dest', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
                ('Tif', models.CharField(max_length=10)),
                ('Otyp', models.CharField(max_length=10)),
                ('FixTags', models.CharField(max_length=400)),
                ('CliOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omautotest.NewClientOrder')),
            ],
        ),
        migrations.CreateModel(
            name='RplStreetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StrOID', models.CharField(max_length=5)),
                ('Qty', models.CharField(max_length=10000)),
                ('Price', models.CharField(max_length=100)),
                ('StrOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omautotest.NewStreetOrder')),
            ],
        ),
        migrations.CreateModel(
            name='StreetExecutionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StrOID', models.CharField(max_length=5)),
                ('ExecType', models.CharField(max_length=10)),
                ('Qty', models.CharField(max_length=10000)),
                ('Price', models.CharField(max_length=100)),
                ('StrOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omautotest.NewStreetOrder')),
            ],
        ),
    ]
