# Generated by Django 2.0.7 on 2018-07-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omautotest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstreetorder',
            name='MergeOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omautotest.CreateMergeOrder'),
        ),
        migrations.AlterField(
            model_name='newclientorder',
            name='FixTags',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='newstreetorder',
            name='CliOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='omautotest.NewClientOrder'),
        ),
        migrations.AlterField(
            model_name='newstreetorder',
            name='FixTags',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
